name: Build macOS
on:
  pull_request:
  workflow_dispatch:
  
jobs:      
  build:
    env:
      VERBOSE: 1
    runs-on: macOS-latest # OS
    steps:    
    - uses: actions/checkout@v2 # pull repository

    - name: Update brew packages
      run: |
        brew update
